Update 2.0

admin.php

1.- Programar el menu que no se repita en todas las paginas, que sea un archivo que se incluya, que se selecccione la pagina en el menu, correspondiente a cada pagina donde se encuentre.

2.- Crear algoritmo de creacion de contraseñas.

//EGRESADOS

1.- Crear el modulo de envio de menajes personales y globales a los egresados del sitio.

2.- Investigar la forma de no mostrar la contraseña (notación de puntos).

3.- Posibles iconos en la secciones mas importantes de datos, que aparezcan con el efecto hover de css.






//CASOS DE EXITO




casosdeexito.php

1.- Dar un colo de fondo a las filas que contengan los casos de exito activos. (verde por ejemplo).

2.- En cuando se apilen mas y mas casos de exito, hacer la petición a la base de datos de forma que aparezcan los casos de exito activos hasta arriba, (eliminaria la actualizacion anterior).

detalle-caso.php

1.- Para el boton de estado (Activo1, Activo2, ...) verificar antes de actualizar o crear nuevo caso de exito si ya estan declarados los 4 casos de exito posibles, si es así confirmar que desea remplazarlo o poner el caso como Inactivo.

2.- Burbuja de mansaje señalando cual es el campo que estan ingresando de forma incorrecta.

3.- Buscar la forma de que las imagenes ya aparezcan cargadas en los casos que ya tengan y un posible vista previa antes de cargar los cambios o el nuevo caso de éxito.

