<div id="pie">
			<div class="container">
				<div class="row">
					<div class="col-xs-12">
						<h3 class="text-center">Universidad Euro Hispanoamericana</h3>
						<h4 class="text-center">Sistema de Seguimiento de Egresados 2016</h4>
					</div>
				</div>
			</div>
		</div>

		<!-- jQuery -->
		<script src="//code.jquery.com/jquery.js"></script>
		<!-- Bootstrap JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
		<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
		<script src="sweetalert.js"></script>
 		<script>

 			 $(document).ready(function() {
 			 	$("#btn-cuadro-1, #btn-cuadro-2, #btn-cuadro-3, #btn-cuadro-4").hide();

 			 	$("#cuadro-datos-1").mouseover(function(){
 			 		$("#btn-cuadro-1").show();
 			 	});
 			 	$("#cuadro-datos-1").mouseout(function(){
 			 		$("#btn-cuadro-1").hide();
 			 	});

 			 	$("#cuadro-datos-2").mouseover(function(){
 			 		$("#btn-cuadro-2").show();
 			 	});
 			 	$("#cuadro-datos-2").mouseout(function(){
 			 		$("#btn-cuadro-2").hide();
 			 	});

 			 	$("#cuadro-datos-3").mouseover(function(){
 			 		$("#btn-cuadro-3").show();
 			 	});
 			 	$("#cuadro-datos-3").mouseout(function(){
 			 		$("#btn-cuadro-3").hide();
 			 	});

 			 	$("#cuadro-datos-4").mouseover(function(){
 			 		$("#btn-cuadro-4").show();
 			 	});
 			 	$("#cuadro-datos-4").mouseout(function(){
 			 		$("#btn-cuadro-4").hide();
 			 	});
 			 	
    
 			});
 		</script>
	</body>
</html>